scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: shadows
      type: laser_filters/ScanShadowsFilter
      params:
        min_angle: 5.0
        max_angle: 179.8
        neighbors: 20
        window: 2
    filter2:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 0
        max_range: 2.0
        max_range_difference: 0.1
        filter_window: 2
    filter3:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: imu_link
        max_x: 0.22
        max_y: 0.18
        max_z: 0.16
        min_x: -0.22
        min_y: -0.18
        min_z: -0.06
        invert: false
