/lslidar_driver_node:
  ros__parameters: 
    frame_id: laser_link                                        
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200                              
    device_ip_difop: 192.168.1.102                       
    msop_port: 2368                                     
    difop_port: 2369                                   
    lidar_name: M10_P                                 
    ceil_increase: -1                                
    angle_disable_min: 0.0                          
    angle_disable_max: 0.0                         
    truncated_mode_: 0                            
    min_range: 0.0                              
    max_range: 200.0                           
    use_gps_ts: false                         
    scan_topic: /scan                        
    interface_selection: serial             
    serial_port_: /dev/wheeltec_lidar      
    high_reflection: false                
    compensation: false			
    pubScan: true                      
    pubPointCloud2: false                   
    pointcloud_topic: /lslidar_point_cloud  
